config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'

  devise_for :users

  resources :artists 
  resources :albums
  resources :songs do 
    post 'search', on: :collection
  end

  resources :favorites, only: [:create, :destroy]

  root to: 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :user
  has_many :albums
  has_one :favorite, as: :favorited

  validates :name, uniqueness: { scope: :user_id, case_sensitive: false }, presence: true
  validates :user, presence: true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_artist, only: [:show, :edit, :update, :destroy]


  # GET /artists
  # GET /artists.json
  def index
    @artists = current_user.artists.order(:name)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = current_user.artists.new artist_params #Artist.new(artist_params.update( user_id: current_user.id ))

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = current_user.artists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @artist.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h4>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="page-header">
  <%= link_to artists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @artist, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing artist</h1>
</div>

<%= render 'form' %>

app/views/artists/index.html.erb
<div class="page-header">
  <%= link_to new_artist_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Artist
  <% end %>
  <h1>Listing artists</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @artists) do |artist| %>
        <%=render partial: "favorites/favorite_row", locals: {record: artist} %> 
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artists/new.html.erb
<div class="page-header">
  <%= link_to artists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New artist</h1>
</div>

<%= render 'form' %>

app/views/artists/show.html.erb
<div class="page-header">
  <%= link_to artists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_artist_path(@artist), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show artist</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @artist.name %></dd>

  <dt>Description:</dt>
  <dd><%= @artist.description %></dd>

</dl>