config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'

  devise_for :users

  resources :artists 
  resources :albums
  resources :songs do 
    post 'search', on: :collection
  end

  resources :favorites, only: [:create, :destroy]

  root to: 'home#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  
  validates :name, uniqueness: { scope: :album_id, case_sensitive: false }, presence: true
  validates :album, presence: true
  validates :user,  presence: true

  has_one :favorite, as: :favorited

  # search songs with a name, album or artist by the term 
  scope :search, ->(term) { 
    joins({album: :artist}).
    where('albums.name like ? OR artists.name like ? OR songs.name like ?', term, term, term).
    order(:name)
  }

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = current_user.songs.order :name
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = current_user.songs.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @search_text = params[:search_text].to_s.strip
    @songs = current_user.songs.search('%' + @search_text + '%') unless @search_text.blank?

    respond_to do |format|
      format.html { render :search }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = current_user.songs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :length, :album_id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @song.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h4>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :length, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :length, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :album_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <% if current_user.albums.none? %>
      Please first <%= link_to 'Add an Album', new_album_path %>
    <% else -%>
      <%= f.collection_select :album_id, current_user.albums.all, :id, :name, {prompt: "Select an album"}, class: "form-control" %>
    <% end -%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/songs/_list.html.erb
<% songs ||= @songs %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Length</th>
            <th>Album</th>
            <th>Artist</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, songs) do |song| %>
            <%=render partial: "favorites/favorite_row", locals: {record: song} %> 
            <td><%= song.name %></td>
            <td><%= song.length %></td>
            <td><%= link_to song.album.name, song.album %></td>
            <td><%= link_to song.album.artist.name, song.album.artist %></td>
            <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/songs/edit.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @song, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing song</h1>
</div>

<%= render 'form' %>

app/views/songs/index.html.erb
<div class="page-header">
  <%= link_to new_song_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Song
  <% end %>
  <h1>Listing songs</h1>
</div>

<%= render "list"%>

app/views/songs/new.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New song</h1>
</div>

<%= render 'form' %>

app/views/songs/search.html.erb
<div class="page-header">
  <h1>Search results for <%=h @search_text %></h1>
</div>

<%= render "list"%>

app/views/songs/show.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_song_path(@song), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show song</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @song.name %></dd>

  <dt>Length:</dt>
  <dd><%= @song.length %></dd>

  <dt>Album:</dt>
  <dd><%= link_to @song.album.name, album_path(@song.album) %></dd>

  <dt>Artist:</dt>
  <dd><%= link_to @song.album.artist.name, artist_path(@song.album) %></dd>

</dl>