config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'

  devise_for :users

  resources :artists 
  resources :albums
  resources :songs do 
    post 'search', on: :collection
  end

  resources :favorites, only: [:create, :destroy]

  root to: 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :artist
  has_many :songs, dependent: :delete_all
  has_one :favorite, as: :favorited, dependent: :delete

  validates :name, uniqueness: { scope: :artist_id, case_sensitive: false }, presence: true
  validates :artist, presence: true
  validates :user, presence: true
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :set_artist

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums.order(:name)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(album_params)
    @album.artist = @artist if @artist

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # This is used for nested views
    def set_artist
      @artist = current_user.artists.find(params[:artist_id]) if params[:artist_id]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = current_user.albums.find(params[:id])
    
      render 404 if @artist && @artist.id != album.artist_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :artist_id, :user_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @album.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h4>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :artist, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <% if current_user.artists.none? %>
      Please first <%= link_to 'Add an Artist', new_artist_path %>
    <% else -%>
      <%= f.collection_select :artist_id, current_user.artists.all, :id, :name, {prompt: "Select an artist"}, class: "form-control" %>
    <% end -%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="page-header">
  <%= link_to albums_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @album, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing album</h1>
</div>

<%= render 'form' %>

app/views/albums/index.html.erb
<div class="page-header">
  <%= link_to new_album_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Album
  <% end %>
  <h1>Listing albums</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Artist</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @albums) do |album| %>
        <%=render partial: "favorites/favorite_row", locals: {record: album} %> 
        <td><%= album.name %></td>
        <td><%= link_to album.artist.name, album.artist %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/albums/new.html.erb
<div class="page-header">
  <%= link_to albums_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New album</h1>
</div>

<%= render 'form' %>

app/views/albums/show.html.erb
<div class="page-header">
  <%= link_to albums_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_album_path(@album), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%=h @album.name %></h1>
  <strong> Artist: </strong><%= @album.artist.name %>

</div>


<h2> Song list </h2>


<%= render partial: "songs/list", locals: { songs: @album.songs }  %>

  <%= link_to new_song_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Song
  <% end %>
  