config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'

  devise_for :users

  resources :artists 
  resources :albums
  resources :songs do 
    post 'search', on: :collection
  end

  resources :favorites, only: [:create, :destroy]

  root to: 'home#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class:"navbar-brand" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render "layouts/navigation_links" %>
      </ul>
      <%= render "layouts/search_bar" %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="<%= 'active' if current_page?(albums_path) %>"><%= link_to 'Albums', albums_path %></li>
<li class="<%= 'active' if current_page?(artists_path) %>"><%= link_to 'Artists', artists_path %></li>
<li class="<%= 'active' if current_page?(songs_path) %>"><%= link_to 'Songs', songs_path %></li>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Favorites <span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li class="<%= 'active' if current_page?(albums_path) %>"><%= link_to 'Albums (NOT WIRED UP)', albums_path %></li>
		<li class="<%= 'active' if current_page?(artists_path) %>"><%= link_to 'Artists (NOT WIRED UP)', artists_path %></li>
		<li class="<%= 'active' if current_page?(songs_path) %>"><%= link_to 'Songs (NOT WIRED UP)', songs_path %></li>
	</ul>
</li>

app/views/layouts/_search_bar.html.erb
<%= form_tag( search_songs_path, role:"search", class: "navbar-form navbar-left") do %>
  <div class="form-group">
    <%= search_field_tag :search_text, @search_text, class:"form-control", placeholder:"Search" %>
  </div>
  <%= submit_tag "Search", class:"btn btn-default" %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyTunes" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mytunes" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>